### ISSUE TITLE
Clean up benchmark output

### ISSUE THREAD

**Issue by upio** [circe/circe-benchmarks#11]
The current benchmark output is difficult to read. The name of the library under test is abbreviated, leaving it up to the reader to figure out which symbol means what. This abbreviation doesn't achieve much, especially since the redundant strings "DecodingBenchmark.decodeFoo" and "EncodingBenchmark.encodeFoo" are always printed. 

Renaming "DecodingBenchmark.decodeFooC" to something like "Decoding.Foo.Circe" would be easier to understand. 

> Benchmark                          Mode  Cnt      Score      Error  Units
> DecodingBenchmark.decodeFoosC     thrpt  100  10161.304 ±  102.923  ops/s
> DecodingBenchmark.decodeFoosA     thrpt  100   2786.826 ±   43.675  ops/s
> DecodingBenchmark.decodeFoosP     thrpt  100   1974.245 ±    9.858  ops/s
> DecodingBenchmark.decodeFoosPico  thrpt  100   2106.936 ±   31.172  ops/s
> DecodingBenchmark.decodeFoosS     thrpt  100   8193.956 ±   38.757  ops/s
> 
> DecodingBenchmark.decodeIntsC     thrpt  100  50399.910 ±  156.052  ops/s
> DecodingBenchmark.decodeIntsA     thrpt  100  20472.141 ±  412.459  ops/s
> DecodingBenchmark.decodeIntsP     thrpt  100  15146.795 ±   68.217  ops/s
> DecodingBenchmark.decodeIntsPico  thrpt  100  15760.650 ±  972.880  ops/s
> DecodingBenchmark.decodeIntsS     thrpt  100  81535.344 ±  293.525  ops/s
> 
> Benchmark                          Mode  Cnt      Score      Error  Units
> EncodingBenchmark.encodeFoosC     thrpt  100   8565.560 ±  107.385  ops/s
> EncodingBenchmark.encodeFoosA     thrpt  100   6736.379 ±   15.906  ops/s
> EncodingBenchmark.encodeFoosP     thrpt  100   1765.981 ±    4.078  ops/s
> EncodingBenchmark.encodeFoosPico  thrpt  100   5779.484 ±   26.803  ops/s
> EncodingBenchmark.encodeFoosS     thrpt  100   6561.330 ±   29.160  ops/s

> 
> EncodingBenchmark.encodeIntsC     thrpt  100  98093.604 ±  223.612  ops/s
> EncodingBenchmark.encodeIntsA     thrpt  100  80580.759 ±  323.298  ops/s
> EncodingBenchmark.encodeIntsP     thrpt  100  29823.703 ±  451.211  ops/s
> EncodingBenchmark.encodeIntsPico  thrpt  100  37110.701 ±  145.859  ops/s
> EncodingBenchmark.encodeIntsS     thrpt  100  43733.808 ± 2810.698  ops/s

**Comment by travisbrown** [comment]
👍, sounds reasonable to me.

**Comment by travisbrown** [comment]
Fixed in #13.
