### ISSUE TITLE
Improvement: comparing Circe and Jackson

### ISSUE THREAD

**Issue by ricardoatsouza** [circe/circe-benchmarks#17]
Hello there,

Here in the company we have been creating services in Scala. Some of them is using Circe, a few others Jackson. Because we want to standardise, I started searching for a benchmark comparing them, which as far as I know, there isn't any.

So I pulled your repo and I included the Jackson benchmark in the code. Then I ran the following commands:

```
sbt "jmh:run -i 10 -wi 10 -f 2 -t 1 io.circe.benchmarks.EncodingBenchmark"
sbt "jmh:run -i 10 -wi 10 -f 2 -t 1 io.circe.benchmarks.DecodingBenchmark"
sbt "jmh:run -i 10 -wi 10 -f 2 -t 1 io.circe.benchmarks.ParsingBenchmark"
```

And here is the result:

**EncodingBenchmark**
```
Benchmark                              Mode  Cnt      Score       Error  Units
EncodingBenchmark.encodeFoosJackson   thrpt   20   4747.077 ±   327.892  ops/s
EncodingBenchmark.encodeFoosCirce     thrpt   20   3534.268 ±   379.940  ops/s
EncodingBenchmark.encodeFoosArgonaut  thrpt   20   2680.524 ±   376.456  ops/s
EncodingBenchmark.encodeFoosSpray     thrpt   20   2567.896 ±   188.934  ops/s
EncodingBenchmark.encodeFoosPlay      thrpt   20   1130.935 ±    91.660  ops/s
EncodingBenchmark.encodeFoos4s        thrpt   20    544.854 ±    99.796  ops/s

EncodingBenchmark.encodeIntsArgonaut  thrpt   20  26761.624 ±  3090.205  ops/s
EncodingBenchmark.encodeIntsJackson   thrpt   20  48284.294 ±  5104.759  ops/s
EncodingBenchmark.encodeIntsCirce     thrpt   20  41756.808 ± 13966.970  ops/s
EncodingBenchmark.encodeIntsSpray     thrpt   20  26407.028 ±   630.188  ops/s
EncodingBenchmark.encodeIntsPlay      thrpt   20  14023.244 ±  3349.223  ops/s
EncodingBenchmark.encodeInts4s        thrpt   20   4494.176 ±   353.332  ops/s
```

**DecodingBenchmark**
```
Benchmark                              Mode  Cnt      Score      Error  Units
DecodingBenchmark.decodeFoosCirce     thrpt   20   6077.733 ±  312.529  ops/s
DecodingBenchmark.decodeFoosSpray     thrpt   20   3148.257 ±   93.745  ops/s
DecodingBenchmark.decodeFoosJackson   thrpt   20   2522.578 ±  109.721  ops/s
DecodingBenchmark.decodeFoosArgonaut  thrpt   20   1538.814 ±   74.439  ops/s
DecodingBenchmark.decodeFoosPlay      thrpt   20   1389.449 ±   49.782  ops/s
DecodingBenchmark.decodeFoos4s        thrpt   20   1073.019 ±   45.923  ops/s

DecodingBenchmark.decodeIntsSpray     thrpt   20  50820.965 ± 4725.008  ops/s
DecodingBenchmark.decodeIntsCirce     thrpt   20  30170.457 ±  734.433  ops/s
DecodingBenchmark.decodeIntsJackson   thrpt   20  27444.723 ±  632.239  ops/s
DecodingBenchmark.decodeIntsPlay      thrpt   20  11464.960 ±  814.165  ops/s
DecodingBenchmark.decodeIntsArgonaut  thrpt   20  11080.127 ±  943.851  ops/s
DecodingBenchmark.decodeInts4s        thrpt   20   8058.288 ±  565.929  ops/s
```

**ParsingBenchmark**
```
Benchmark                            Mode  Cnt      Score      Error  Units
ParsingBenchmark.parseFoosJackson   thrpt   20   3803.383 ±  143.685  ops/s
ParsingBenchmark.parseFoosSpray     thrpt   20   2605.591 ±  144.410  ops/s
ParsingBenchmark.parseFoosCirce     thrpt   20   2270.309 ±   73.920  ops/s
ParsingBenchmark.parseFoosPlay      thrpt   20   2109.209 ±  174.506  ops/s
ParsingBenchmark.parseFoos4s        thrpt   20   2051.549 ±   63.897  ops/s
ParsingBenchmark.parseFoosArgonaut  thrpt   20   1703.708 ±   72.967  ops/s

ParsingBenchmark.parseIntsJackson   thrpt   20  30286.016 ± 1523.783  ops/s
ParsingBenchmark.parseIntsCirce     thrpt   20  17211.614 ±  667.697  ops/s
ParsingBenchmark.parseIntsSpray     thrpt   20  14300.657 ±  754.562  ops/s
ParsingBenchmark.parseIntsArgonaut  thrpt   20  10315.202 ±  429.667  ops/s
ParsingBenchmark.parseIntsPlay      thrpt   20   9455.802 ±  468.896  ops/s
ParsingBenchmark.parseInts4s        thrpt   20   6536.145 ±  239.060  ops/s
```

I want to know if you want this addition in the repo. If yes, I will create a pull request. 
Let me know what you think of it :)

**Comment by travisbrown** [comment]
Yes, this looks like a good addition! Just to be clear—this is using Jackson for parsing and decoding, as opposed to for parsing via circe-jackson?

**Comment by travisbrown** [comment]
@ricardoatsouza Sounds good. I'm just curious—how do these numbers look to you in the context of your evaluation? For me circe is close enough to Jackson to justify its use in most cases (especially since the case class decoding benchmark is often the most realistic, and circe actually wins there), but I know that might not be the case for everyone.

**Comment by ricardoatsouza** [comment]
We decided to do this benchmark because our services are going to be processing large amounts of data. And therefore would be nice to see the comparison between Circe and Jackson (since both are currently in use) before choosing for one of them. I'm happy to see that they perform very close to each other. :)

Looking at these numbers, the decision of taking one or another mostly depends on the use case. In ours, for example, one of our services is decoding tons of messages every minute. And this particular service is implemented in Jackson. Circe seems more promising for this task. :)

At first, our idea was to standardise: use only one JSON library: Circe or Jackson. But it seems that a better idea is to explore the strength of each and use them accordingly.

**Comment by ricardoatsouza** [comment]
@travisbrown Let me know if you want me to push the changes into the repo. I would appreciate your reviews. :)

**Comment by travisbrown** [comment]
@ricardoatsouza Yes, a pull request would be welcome, thanks!

**Comment by ricardoatsouza** [comment]
I just need permission to push it to the repo. :)

--
Ricardo Souza

**Comment by travisbrown** [comment]
@ricardoatsouza If you create a fork (with the button in the near-top right of the main repo page) and then push a branch to that fork, you can open a pull request, which makes things a little simpler, especially for review.

**Comment by ricardoatsouza** [comment]
@travisbrown Done. Thanks, I totally forgot that it is possible via fork :)

**Comment by travisbrown** [comment]
Added in #18.
